export const SET_USER_INFO = "SET_USER_INFO";
export const SET_NEW_USER = "SET_NEW_USER";
export const SET_ALL_CONTACTS_PAGE = "SET_ALL_CONTACTS_PAGE";
export const CHANGE_CURRENT_CHAT_USER = "CHANGE_CURRENT_CHAT_USER";
export const SET_MESSAGES = "SET_MESSAGES";

