export const SET_USER_INFO = "SET_USER_INFO";
export const SET_NEW_USER = "SET_NEW_USER";
export const SET_ALL_CONTACTS_PAGE = "SET_ALL_CONTACTS_PAGE";
export const CHANGE_CURRENT_CHAT_USER = "CHANGE_CURRENT_CHAT_USER";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_SOCKET = "SET_SOCKET";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const SET_MESSAGE_SEARCH = "SET_MESSAGE_SEARCH";
export const SET_USER_CONTACTS = "SET_USER_CONTACTS";
export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const SET_CONTACT_SEARCH = "SET_CONTACT_SEARCH";

