export const SET_USER_INFO = "SET_USER_INFO";
export const SET_NEW_USER = "SET_NEW_USER";
export const SET_ALL_CONTACTS_PAGE = "SET_ALL_CONTACTS_PAGE";
export const SET_PROFILE_PAGE = "SET_PROFILE_PAGE";
export const CHANGE_CURRENT_CHAT_USER = "CHANGE_CURRENT_CHAT_USER";
export const IS_ON_SAME_CHAT = "IS_ON_SAME_CHAT";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_REACTION = "SET_REACTION";
export const SET_SOCKET = "SET_SOCKET";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const REPLY_TO_MESSAGE = "REPLY_TO_MESSAGE";
export const SET_MESSAGE_SEARCH = "SET_MESSAGE_SEARCH";
export const SET_USER_CONTACTS = "SET_USER_CONTACTS";
export const UPDATE_USER_CONTACTS_ON_RECEIVE = "UPDATE_USER_CONTACTS_ON_RECEIVE";
export const UPDATE_USER_CONTACTS_ON_SEND = "UPDATE_USER_CONTACTS_ON_SEND";
export const UPDATE_MESSAGE_STATUS = "UPDATE_MESSAGE_STATUS";
export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const SET_CONTACT_SEARCH = "SET_CONTACT_SEARCH";
export const SET_VIDEO_CALL = "SET_VIDEO_CALL";
export const SET_VOICE_CALL = "SET_VOICE_CALL";
export const END_CALL = "ENd_CALL";
export const SET_INCOMING_VOICE_CALL = "SET_INCOMING_VOICE_CALL";
export const SET_INCOMING_VIDEO_CALL = "SET_INCOMING_VIDEO_CALL";
export const SET_IS_TYPING = "IS_TYPING";
export const SET_NOT_TYPING = "SET_NOT_TYPING";

export const SET_EXIT_CHAT = "SET_EXIT_CHAT";


export const SHOW_CHATLIST = "SHOW_CHATLIST";